Text Preprocessing 

nltk library 

In [6]:
paragraph="""Mahendra Singh Dhoni (/məˈheɪndrə ˈsɪŋ dhæˈnɪ/ ⓘ; born 7 July 1981) is an Indian professional cricketer who plays as a right-handed batter and a wicket-keeper. Widely regarded as one of the most prolific wicket-keeper batsmen and captains and one of the greatest ODI batsmen, he represented the Indian cricket team and was the captain of the side in limited overs formats from 2007 to 2017 and in test cricket from 2008 to 2014. Dhoni has captained the most international matches and is the most successful Indian captain. He has led India to victory in the 2007 ICC World Twenty20, the 2011 Cricket World Cup, and the 2013 ICC Champions Trophy, being the only captain to win three different limited overs ICC tournaments. He also led the teams that won the Asia Cup in 2010, 2016 and was a member of the title winning squad in 2018"""

In [7]:
import nltk
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [8]:
print(nltk.data.path)

['C:\\Users\\huzef/nltk_data', 'c:\\Users\\huzef\\anaconda3\\nltk_data', 'c:\\Users\\huzef\\anaconda3\\share\\nltk_data', 'c:\\Users\\huzef\\anaconda3\\lib\\nltk_data', 'C:\\Users\\huzef\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']


In [9]:
nltk.download('punkt')


[nltk_data] Downloading package punkt to
[nltk_data]     c:\Users\huzef\anaconda3\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [10]:
## Tokenization
sentence=nltk.sent_tokenize(paragraph)

In [11]:
sentence

['Mahendra Singh Dhoni (/məˈheɪndrə ˈsɪŋ dhæˈnɪ/ ⓘ; born 7 July 1981) is an Indian professional cricketer who plays as a right-handed batter and a wicket-keeper.',
 'Widely regarded as one of the most prolific wicket-keeper batsmen and captains and one of the greatest ODI batsmen, he represented the Indian cricket team and was the captain of the side in limited overs formats from 2007 to 2017 and in test cricket from 2008 to 2014.',
 'Dhoni has captained the most international matches and is the most successful Indian captain.',
 'He has led India to victory in the 2007 ICC World Twenty20, the 2011 Cricket World Cup, and the 2013 ICC Champions Trophy, being the only captain to win three different limited overs ICC tournaments.',
 'He also led the teams that won the Asia Cup in 2010, 2016 and was a member of the title winning squad in 2018']

Cleaning the Text


In [12]:
import re

In [13]:
corpus=[]
for i in range(len(sentence)):
    review=re.sub('[^a-zA-Z]',' ',sentence[i])
    review=review.lower()
    corpus.append(review)
corpus


['mahendra singh dhoni   m  he ndr   s   dh  n      born   july       is an indian professional cricketer who plays as a right handed batter and a wicket keeper ',
 'widely regarded as one of the most prolific wicket keeper batsmen and captains and one of the greatest odi batsmen  he represented the indian cricket team and was the captain of the side in limited overs formats from      to      and in test cricket from      to      ',
 'dhoni has captained the most international matches and is the most successful indian captain ',
 'he has led india to victory in the      icc world twenty    the      cricket world cup  and the      icc champions trophy  being the only captain to win three different limited overs icc tournaments ',
 'he also led the teams that won the asia cup in            and was a member of the title winning squad in     ']

Stemming

In [14]:
stemmer=PorterStemmer()


In [15]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     c:\Users\huzef\anaconda3\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [16]:
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(stemmer.stem(word))

mahendra
singh
dhoni
ndr
dh
n
born
juli
indian
profession
cricket
play
right
hand
batter
wicket
keeper
wide
regard
one
prolif
wicket
keeper
batsmen
captain
one
greatest
odi
batsmen
repres
indian
cricket
team
captain
side
limit
over
format
test
cricket
dhoni
captain
intern
match
success
indian
captain
led
india
victori
icc
world
twenti
cricket
world
cup
icc
champion
trophi
captain
win
three
differ
limit
over
icc
tournament
also
led
team
asia
cup
member
titl
win
squad


Stopwords

Lemmatization

In [17]:

from nltk.stem import WordNetLemmatizer

In [18]:
lemmatizer=WordNetLemmatizer()

In [19]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     c:\Users\huzef\anaconda3\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [20]:
for i in corpus:
    words=nltk.word_tokenize(i)
    for word in words:
        if word not in set(stopwords.words('english')):
            print(lemmatizer.lemmatize(word))

mahendra
singh
dhoni
ndr
dh
n
born
july
indian
professional
cricketer
play
right
handed
batter
wicket
keeper
widely
regarded
one
prolific
wicket
keeper
batsman
captain
one
greatest
odi
batsman
represented
indian
cricket
team
captain
side
limited
over
format
test
cricket
dhoni
captained
international
match
successful
indian
captain
led
india
victory
icc
world
twenty
cricket
world
cup
icc
champion
trophy
captain
win
three
different
limited
over
icc
tournament
also
led
team
asia
cup
member
title
winning
squad


Stopwords in lemmatization

In [21]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     c:\Users\huzef\anaconda3\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [22]:
corpus=[]
for i in range(len(sentence)):
    rev=re.sub('[^a-zA-Z]', ' ',sentence[i])
    rev=rev.lower()
    rev=rev.split()
    rev=[lemmatizer.lemmatize(word) for word in rev if not word in set(stopwords.words('english'))]
    rev=' '.join(rev)
    corpus.append(rev)

Bag of Word

In [23]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()#n _gram

N Grams


In [24]:
cv1=CountVectorizer(ngram_range=(3,3))  ## creates a tri grams 
cv2=CountVectorizer(ngram_range=(2,3))# creates a bi grams and tri grams

In [25]:
X=cv.fit_transform(corpus)
Y=cv1.fit_transform(corpus)
Z=cv2.fit_transform(corpus)

In [26]:
cv.vocabulary_# gives the indices of the words 

{'mahendra': 25,
 'singh': 39,
 'dhoni': 12,
 'ndr': 28,
 'dh': 11,
 'born': 4,
 'july': 21,
 'indian': 19,
 'professional': 33,
 'cricketer': 9,
 'play': 32,
 'right': 37,
 'handed': 16,
 'batter': 3,
 'wicket': 50,
 'keeper': 22,
 'widely': 51,
 'regarded': 35,
 'one': 30,
 'prolific': 34,
 'batsman': 2,
 'captain': 5,
 'greatest': 15,
 'odi': 29,
 'represented': 36,
 'cricket': 8,
 'team': 42,
 'side': 38,
 'limited': 24,
 'over': 31,
 'format': 14,
 'test': 43,
 'captained': 6,
 'international': 20,
 'match': 26,
 'successful': 41,
 'led': 23,
 'india': 18,
 'victory': 49,
 'icc': 17,
 'world': 54,
 'twenty': 48,
 'cup': 10,
 'champion': 7,
 'trophy': 47,
 'win': 52,
 'three': 44,
 'different': 13,
 'tournament': 46,
 'also': 0,
 'asia': 1,
 'member': 27,
 'title': 45,
 'winning': 53,
 'squad': 40}

In [27]:
cv1.vocabulary_

{'mahendra singh dhoni': 35,
 'singh dhoni ndr': 51,
 'dhoni ndr dh': 18,
 'ndr dh born': 38,
 'dh born july': 16,
 'born july indian': 5,
 'july indian professional': 29,
 'indian professional cricketer': 27,
 'professional cricketer play': 45,
 'cricketer play right': 13,
 'play right handed': 44,
 'right handed batter': 49,
 'handed batter wicket': 22,
 'batter wicket keeper': 4,
 'widely regarded one': 61,
 'regarded one prolific': 47,
 'one prolific wicket': 41,
 'prolific wicket keeper': 46,
 'wicket keeper batsman': 60,
 'keeper batsman captain': 30,
 'batsman captain one': 2,
 'captain one greatest': 6,
 'one greatest odi': 40,
 'greatest odi batsman': 21,
 'odi batsman represented': 39,
 'batsman represented indian': 3,
 'represented indian cricket': 48,
 'indian cricket team': 26,
 'cricket team captain': 11,
 'team captain side': 54,
 'captain side limited': 7,
 'side limited over': 50,
 'limited over format': 33,
 'over format test': 42,
 'format test cricket': 20,
 'dhoni 

In [28]:
cv2.vocabulary_

{'mahendra singh': 71,
 'singh dhoni': 103,
 'dhoni ndr': 36,
 'ndr dh': 77,
 'dh born': 32,
 'born july': 10,
 'july indian': 60,
 'indian professional': 56,
 'professional cricketer': 91,
 'cricketer play': 26,
 'play right': 89,
 'right handed': 99,
 'handed batter': 44,
 'batter wicket': 8,
 'wicket keeper': 122,
 'mahendra singh dhoni': 72,
 'singh dhoni ndr': 104,
 'dhoni ndr dh': 37,
 'ndr dh born': 78,
 'dh born july': 33,
 'born july indian': 11,
 'july indian professional': 61,
 'indian professional cricketer': 57,
 'professional cricketer play': 92,
 'cricketer play right': 27,
 'play right handed': 90,
 'right handed batter': 100,
 'handed batter wicket': 45,
 'batter wicket keeper': 9,
 'widely regarded': 124,
 'regarded one': 95,
 'one prolific': 83,
 'prolific wicket': 93,
 'keeper batsman': 62,
 'batsman captain': 4,
 'captain one': 12,
 'one greatest': 81,
 'greatest odi': 42,
 'odi batsman': 79,
 'batsman represented': 6,
 'represented indian': 97,
 'indian cricket': 

In [29]:
corpus[0]

'mahendra singh dhoni ndr dh n born july indian professional cricketer play right handed batter wicket keeper'

In [30]:
X[0].toarray()

array([[0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
        1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]], dtype=int64)

In [31]:
Y[0].toarray() # tri grams

array([[0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int64)

In [32]:
Z[0].toarray() # bi & tri grams

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]], dtype=int64)

TF-IDF


In [33]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tf=TfidfVectorizer(ngram_range=(2,2),max_features=3)#max_feature=n--a top n frequencies are considre 
x=tf.fit_transform(corpus),

In [35]:
x[0].toarray()

array([[0.        , 0.        , 1.        ],
       [0.53177225, 0.659118  , 0.53177225],
       [0.        , 0.        , 0.        ],
       [1.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        ]])