In [4]:
!pip install tensorflow-gpu


  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      Traceback (most recent call last):
        File "C:\Users\huzef\anaconda3\Lib\site-packages\packaging\requirements.py", line 36, in __init__
          parsed = _parse_requirement(requirement_string)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\huzef\anaconda3\Lib\site-packages\packaging\_parser.py", line 62, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\huzef\anaconda3\Lib\site-packages\packaging\_parser.py", line 80, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\huzef\anaconda3\Lib\site-packages\packaging\_parser.py"

In [16]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [17]:
from tensorflow.keras.preprocessing.text import one_hot

In [18]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [19]:
voc_size=500

One Hot REpresentation

In [20]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[414, 49, 486, 117], [414, 49, 486, 434], [414, 449, 486, 430], [203, 411, 179, 157, 102], [203, 411, 179, 157, 146], [425, 414, 214, 486, 449], [385, 186, 37, 157]]


In [21]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [32]:
sent_len=8
embedded_doc=pad_sequences(onehot_repr,padding="pre",maxlen=sent_len)
print(embedded_doc)

[[  0   0   0   0 414  49 486 117]
 [  0   0   0   0 414  49 486 434]
 [  0   0   0   0 414 449 486 430]
 [  0   0   0 203 411 179 157 102]
 [  0   0   0 203 411 179 157 146]
 [  0   0   0 425 414 214 486 449]
 [  0   0   0   0 385 186  37 157]]


In [33]:
#dimensions
dim=10

In [34]:
model=Sequential()
model.add(Embedding(voc_size,10))
model.compile('adam','mse')

In [35]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
embedded_doc[0]

array([  0,   0,   0,   0, 414,  49, 486, 117])

In [38]:
print(model.predict(embedded_doc))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 757ms/step
[[[ 0.00266875  0.03255277 -0.04025984  0.0240261   0.0389745
   -0.04191992  0.000473    0.00957678  0.00560206 -0.04640858]
  [ 0.00266875  0.03255277 -0.04025984  0.0240261   0.0389745
   -0.04191992  0.000473    0.00957678  0.00560206 -0.04640858]
  [ 0.00266875  0.03255277 -0.04025984  0.0240261   0.0389745
   -0.04191992  0.000473    0.00957678  0.00560206 -0.04640858]
  [ 0.00266875  0.03255277 -0.04025984  0.0240261   0.0389745
   -0.04191992  0.000473    0.00957678  0.00560206 -0.04640858]
  [ 0.02264689  0.04928073  0.03313137 -0.03283749  0.0261916
   -0.01794715 -0.01793488  0.01150024  0.03117755  0.0224165 ]
  [ 0.03150551 -0.01856704  0.02540919 -0.0039235  -0.01070295
    0.03588111 -0.02603722  0.02146127 -0.00918783  0.02040936]
  [-0.02919588 -0.00597842 -0.02951008 -0.00926619  0.01832988
   -0.02794929 -0.04598344  0.01089153  0.02169421  0.00302304]
  [ 0.02983144 -0.04743505  0.0081872   0.0477138  -0.03170139
    0.02540473

In [39]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [41]:
one_h=[one_hot(words,voc_size)for words in sent]
print(one_h)

[[414, 404, 209, 179, 61, 134], [353, 434, 209, 298, 89, 326], [203, 271, 460, 447], [414, 455, 209, 368, 414, 410], [434, 67, 343, 209, 298, 89, 326], [253, 209, 298, 89, 427, 374]]


In [44]:
sent_len=8
embedded_docs=pad_sequences(one_h,padding='pre',maxlen=sent_len)
embedded_docs

array([[  0,   0, 414, 404, 209, 179,  61, 134],
       [  0,   0, 353, 434, 209, 298,  89, 326],
       [  0,   0,   0,   0, 203, 271, 460, 447],
       [  0,   0, 414, 455, 209, 368, 414, 410],
       [  0, 434,  67, 343, 209, 298,  89, 326],
       [  0,   0, 253, 209, 298,  89, 427, 374]])

In [46]:
model1=Sequential()
model1.add(Embedding(voc_size,10))
model1.compile('adam','mse')

In [47]:
model.summary()


Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_5 (Embedding)         │ (7, 8, 10)             │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 232ms/step


array([[[ 2.6687495e-03,  3.2552768e-02, -4.0259838e-02,  2.4026100e-02,
          3.8974497e-02, -4.1919924e-02,  4.7300011e-04,  9.5767751e-03,
          5.6020617e-03, -4.6408582e-02],
        [ 2.6687495e-03,  3.2552768e-02, -4.0259838e-02,  2.4026100e-02,
          3.8974497e-02, -4.1919924e-02,  4.7300011e-04,  9.5767751e-03,
          5.6020617e-03, -4.6408582e-02],
        [ 2.2646893e-02,  4.9280729e-02,  3.3131372e-02, -3.2837488e-02,
          2.6191603e-02, -1.7947149e-02, -1.7934881e-02,  1.1500239e-02,
          3.1177547e-02,  2.2416499e-02],
        [ 3.1517897e-02,  1.5173111e-02,  3.5823356e-02, -1.6163230e-02,
          1.5589584e-02,  3.6471892e-02, -3.9093256e-02, -7.2243921e-03,
         -4.6100244e-03,  8.4027424e-03],
        [-1.6003001e-02,  2.7172450e-02,  2.6603866e-02, -4.7652103e-02,
         -3.7470937e-02, -4.5784127e-02, -3.9107479e-02,  6.2841885e-03,
          5.0613396e-03, -2.2500642e-03],
        [ 3.5766963e-02,  4.2998385e-02,  2.9124413e-02,  1.